[build]
  base = "/"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

# Add this section to handle secrets scanning
[build.environment]
  SECRETS_SCAN_ENABLED = "false" 